---
title: "Exemplo de gráficos"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo    = FALSE,
  message = FALSE,
  warning = FALSE)

```


```{r pacotes, include=FALSE}
library(tidyverse)
library(ggplot2)

```


```{r entrada-de-dados, include=FALSE}
data(mtcars); force(mtcars) # Desempenho e consumo de combustível de 32 carros (anos 1973-1974).
data(iris); force(iris) # Medidas de sépalas e pétalas de 3 espécies de flores Iris.
data(airquality); force(airquality) # Dados diários de qualidade do ar em Nova York (1973).
data(quakes); force(quakes) # Localização e magnitude de 1000 terremotos perto de Fiji.

```


```{r, fig.width=8, fig.height=6, dpi=600}
ggplot(mtcars, aes(x = mpg)) +
  geom_histogram(
    bins = 20,
    fill = "#4b9b69",          # Cor das barras
    color = "white",             # Cor da borda
    na.rm=TRUE) +
  labs(
    title = "Tipo de Gráfico: Histograma",
    subtitle = "Variável: mpg",
    x = "mpg",
    y = "Frequência",
    caption = "Banco de dados: mtcars") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 12L,
    face = "bold",
    hjust = 0.5))

```


```{r, fig.width=8, fig.height=6, dpi=600}
ggplot(mtcars, aes(x = cyl)) +
  geom_bar(
    fill = "#4b9b69",          # Cor das barras
    color = "white",             # Cor da borda
    na.rm=TRUE) +
  labs(
    title = "Tipo de Gráfico: Barras",
    subtitle = "Variável: cyl",
    x = "cyl",
    y = "Frequência",
    caption = "Banco de dados: mtcars") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 12L,
    face = "bold",
    hjust = 0.5))

```


```{r, fig.width=8, fig.height=6, dpi=600}
ggplot(mtcars, aes(x = wt, y = mpg)) +
  geom_point(aes(color = factor(cyl)), size = 3) +
  geom_smooth(method = "lm", se = TRUE, color = "black") +
  labs(
    title = "Tipo de Gráfico: Dispersão",
    subtitle = "Variáveis: wt, mpg",
    x = "Peso",
    y = "MPG",
    color = "Cilindros",
    caption = "Banco de dados: mtcars") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 12L,
    face = "bold",
    hjust = 0.5))

```








